port: 8080

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 86400

mongo:
  uri: "mongodb://localhost:27017/"
  name: "tododb"
  todo_collection: "todos"
  user_collection: "users"